HW_2
odessabear/EPAMLab pull request #2
Opened 2022-01-26 12:59 UTC by odessabear

Homework 2 for check

2022-01-31 18:23 UTC, OlehIlchyshyn requested changes
Hi Oleksandr!

Please fix the issue with redundant bean creation due to component scan, and refactor validation logic to avoid duplication. Besides that, I don't have any other major objection, well done overall)

Feel free to ask any questions if you have some

2022-01-31 18:23 UTC, OlehIlchyshyn commented on src/main/java/com/epam/spring/homework2/beans/BeanA.java
> +    public BeanA(){}
NIT: For the sake of readability, you can omit the creation of default constructor explicitly, as it is automatically generated by java compiler

2022-01-31 18:23 UTC, OlehIlchyshyn commented on src/main/java/com/epam/spring/homework2/beans/BeanA.java
> +    }
All your beans are validated in the same way, so it makes sense to get that validation logic out of beans to avoid duplication. Separate validator class to encapsulate the validation itself would fit nice for this use case)
Also, despite logging validation result, consider returning some value from validate method(), for example, boolean. It could serve as an indicator whether the validation was successful or not, and then consumers of that validate method could decide what should be done in that case, e.g. some exception should be thrown.

2022-01-31 18:23 UTC, OlehIlchyshyn commented on src/main/java/com/epam/spring/homework2/beans/BeanA.java
> +@Component
NIT: @component annotation can be omitted here, as we are creating beans explicitly in the configuration. This annotation could be useful if auto-configuration of beans was enabled, in that case package scan would be performed to find those @component classes and to use them as beans definitions.
Same applies to all beanX in your project.

2022-01-31 18:23 UTC, OlehIlchyshyn commented on src/main/java/com/epam/spring/homework2/beans/OtherBeanFactoryPostProcessor.java
> +        configurableListableBeanFactory.getBeanDefinition("beanB").setInitMethodName("otherCustomInitMethod");
`.getBeanDefinition("beanB")` won't work because your bean name is `'getBeanB',` the same as the method which creates the BeanB instance in your config.

2022-01-31 18:23 UTC, OlehIlchyshyn commented on src/main/java/com/epam/spring/homework2/beans/OtherBeanFactoryPostProcessor.java
> +        configurableListableBeanFactory.getBeanDefinition("beanB").setInitMethodName("otherCustomInitMethod");
Btw, just noticed, you have both @ComponentScan and explicit bean construction inside the config, that way you would have two beans of class BeanB - one with 'getBeanB' name and other called 'beanB'. That's the reason why you haven't got en exception here.

2022-01-31 18:23 UTC, OlehIlchyshyn commented on src/main/java/com/epam/spring/homework2/config/SecondBeansConfig.java
> +@ComponentScan("com.epam.spring.homework2.beans")
Please remove that, you are creating two instances of each bean class.

2022-01-31 18:23 UTC, OlehIlchyshyn commented on src/main/java/com/epam/spring/homework2/config/FirstBeansConfig.java
> +    public BeanB getBeanB() {
Consider naming methods which return beans just like you would want your beans to be named, or you could also provide bean name in props of @Bean annotation

2022-02-03 22:42 UTC, odessabear commented on src/main/java/com/epam/spring/homework2/beans/BeanA.java
> +    }
Hey Oleh, I've done required changes and I hope they are correct. Thanks!

2022-02-04 09:46 UTC, OlehIlchyshyn requested changes
I have left few minor comments, and also please implement task12 (print configuration of the each bean present in the context (see [java-doc for getBeanDefinition](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/support/GenericApplicationContext.html#getBeanDefinition-java.lang.String-)). 
Thanks for addressing previous comments and have a great weekend!

2022-02-04 09:46 UTC, OlehIlchyshyn commented on src/main/java/com/epam/spring/homework2/beans/BeanB.java
> +    public BeanB(){}
this particular constructor and BeanC, BeanD constructors could be safely removed, see https://github.com/odessabear/EPAMLab/pull/2#discussion_r795932869

2022-02-04 09:46 UTC, OlehIlchyshyn commented on src/main/java/com/epam/spring/homework2/validator/BeansValidatorImpl.java
> +            System.out.println("Bean: " + bean.getName() + " and " + bean.getValue() + " is not valid");
Having a separate message for each field being validated could be more meaningful - that way end users would know that, for example, validation failed because value was positive just by looking at the logs.

2022-02-04 22:07 UTC, odessabear commented on src/main/java/com/epam/spring/homework2/beans/BeanB.java
> +    public BeanB(){}
Oops, I thought I did it :-)

2022-02-04 22:07 UTC, odessabear commented on src/main/java/com/epam/spring/homework2/validator/BeansValidatorImpl.java
> +            System.out.println("Bean: " + bean.getName() + " and " + bean.getValue() + " is not valid");
I hope this is what is needed.
Have a great weekend, too.

2022-02-07 09:25 UTC, OlehIlchyshyn commented on src/main/java/com/epam/spring/homework2/ApplicationRunner.java
> +            System.out.println(beanDefinitionName);
Task #12 implementation is still missing 
```suggestion
            System.out.println("Bean name: " + beanDefinitionName);
            System.out.println("Bean definition: " + applicationContext.getBeanDefinition(beanDefinitionName));
```

2022-02-07 09:25 UTC, OlehIlchyshyn approved these changes
Hi! I left a comment on how task 12 should be implemented. I don't have any other comments left, everything else if fine and polished :)

2022-02-07 11:31 UTC, merged